// Code generated by gen.py. DO NOT EDIT.

package expconf

import (
	"github.com/santhosh-tekuri/jsonschema/v2"

	"github.com/determined-ai/determined/master/pkg/schemas"
)

func (l LogSignalV0) Label() string {
	return l.RawLabel
}

func (l *LogSignalV0) SetLabel(val string) {
	l.RawLabel = val
}

func (l LogSignalV0) ParsedSchema() interface{} {
	return schemas.ParsedLogSignalV0()
}

func (l LogSignalV0) SanityValidator() *jsonschema.Schema {
	return schemas.GetSanityValidator("http://determined.ai/schemas/expconf/v0/log-signal.json")
}

func (l LogSignalV0) CompletenessValidator() *jsonschema.Schema {
	return schemas.GetCompletenessValidator("http://determined.ai/schemas/expconf/v0/log-signal.json")
}
